version: '3'

services:

  api:
    build: ./api
    command: npm run start
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - PORT=9000
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db

  api_db:
    image: mongo:latest
    volumes:
      - mongodb_volume:/data/db

volumes:
  mongodb_volume:
